<a href="https://colab.research.google.com/github/vipashaaV321/Collaborative-Food-Recipe-Recommendation-System/blob/Vipasha/Copy_of_SVD_Approach_20min.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
Base_path ='/content/drive/MyDrive/Data/RS2'

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
from scipy.sparse import csr_matrix

# convert the input matrix to a sparse matrix
sparse_matrix = csr_matrix(matrix)

# define the batch size
batch_size = 1000

# compute the similarity matrix between items incrementally
item_similarities = csr_matrix((matrix.shape[1], matrix.shape[1]), dtype=np.float32)
for i in range(0, matrix.shape[1], batch_size):
    print(f"Processing items {i}-{i+batch_size-1}")
    batch = sparse_matrix[:, i:i+batch_size]
    print(batch.shape)
    batch_item_similarities = batch.T.dot(Vt)
    item_similarities[i:i+batch_size, :] = batch_item_similarities

In [ ]:
print(Vt.T.shape)

###### Getting Ram Crashed try to use chuncked data

In [ ]:
# define the batch size
batch_size = 1000

# compute the similarity matrix between items incrementally
item_similarities = np.zeros((matrix.shape[1], matrix.shape[1]))
for i in range(0, matrix.shape[1], batch_size):
    print(f"Processing items {i}-{i+batch_size-1}")
    batch = matrix[:, i:i+batch_size]
    batch_item_similarities = np.dot(Vt.T[i:i+batch_size, :], Vt.T)
    item_similarities[i:i+batch_size, :] = batch_item_similarities

In [ ]:
item_similarities = np.dot(Vt.T, Vt)

In [ ]:
Recipes=pd.read_csv(Base_path+"/RAW_recipes.csv")

In [ ]:
df = Recipes[Recipes['minutes']<=20]

In [ ]:
df['minutes'].max()

20

In [ ]:
Interactions = pd.read_csv(Base_path+"/interactions_train.csv")

In [ ]:

Merged_Data2 = pd.merge(Recipes,Interactions, how="inner", left_on = 'id', right_on= 'recipe_id')
Merged_Data2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 698901 entries, 0 to 698900
Data columns (total 18 columns):
 #   Column          Non-Null Count   Dtype  
---  ------          --------------   -----  
 0   name            698901 non-null  object 
 1   id              698901 non-null  int64  
 2   minutes         698901 non-null  int64  
 3   contributor_id  698901 non-null  int64  
 4   submitted       698901 non-null  object 
 5   tags            698901 non-null  object 
 6   nutrition       698901 non-null  object 
 7   n_steps         698901 non-null  int64  
 8   steps           698901 non-null  object 
 9   description     684627 non-null  object 
 10  ingredients     698901 non-null  object 
 11  n_ingredients   698901 non-null  int64  
 12  user_id         698901 non-null  int64  
 13  recipe_id       698901 non-null  int64  
 14  date            698901 non-null  object 
 15  rating          698901 non-null  float64
 16  u               698901 non-null  int64  
 17  i         

In [ ]:
Merged_Data2

name      id  minutes  \
0       arriba   baked winter squash mexican style  137739       55   
1       arriba   baked winter squash mexican style  137739       55   
2       arriba   baked winter squash mexican style  137739       55   
3                 a bit different  breakfast pizza   31490       30   
4                 a bit different  breakfast pizza   31490       30   
...                                            ...     ...      ...   
698896                   zydeco ya ya deviled eggs  308080       40   
698897                   zydeco ya ya deviled eggs  308080       40   
698898                   zydeco ya ya deviled eggs  308080       40   
698899                   zydeco ya ya deviled eggs  308080       40   
698900                   zydeco ya ya deviled eggs  308080       40   

        contributor_id   submitted  \
0                47892  2005-09-16   
1                47892  2005-09-16   
2                47892  2005-09-16   
3                26278  2002-06-17   
4                26278  2002-06-17   
...                ...         ...   
698896           37779  2008-06-07   
698897           37779  2008-06-07   
698898           37779  2008-06-07   
698899           37779  2008-06-07   
698900           37779  2008-06-07   

                                                     tags  \
0       ['60-minutes-or-less', 'time-to-make', 'course...   
1       ['60-minutes-or-less', 'time-to-make', 'course...   
2       ['60-minutes-or-less', 'time-to-make', 'course...   
3       ['30-minutes-or-less', 'time-to-make', 'course...   
4       ['30-minutes-or-less', 'time-to-make', 'course...   
...                                                   ...   
698896  ['60-minutes-or-less', 'time-to-make', 'course...   
698897  ['60-minutes-or-less', 'time-to-make', 'course...   
698898  ['60-minutes-or-less', 'time-to-make', 'course...   
698899  ['60-minutes-or-less', 'time-to-make', 'course...   
698900  ['60-minutes-or-less', 'time-to-make', 'course...   

                                        nutrition  n_steps  \
0           [51.5, 0.0, 13.0, 0.0, 2.0, 0.0, 4.0]       11   
1           [51.5, 0.0, 13.0, 0.0, 2.0, 0.0, 4.0]       11   
2           [51.5, 0.0, 13.0, 0.0, 2.0, 0.0, 4.0]       11   
3       [173.4, 18.0, 0.0, 17.0, 22.0, 35.0, 1.0]        9   
4       [173.4, 18.0, 0.0, 17.0, 22.0, 35.0, 1.0]        9   
...                                           ...      ...   
698896       [59.2, 6.0, 2.0, 3.0, 6.0, 5.0, 0.0]        7   
698897       [59.2, 6.0, 2.0, 3.0, 6.0, 5.0, 0.0]        7   
698898       [59.2, 6.0, 2.0, 3.0, 6.0, 5.0, 0.0]        7   
698899       [59.2, 6.0, 2.0, 3.0, 6.0, 5.0, 0.0]        7   
698900       [59.2, 6.0, 2.0, 3.0, 6.0, 5.0, 0.0]        7   

                                                    steps  \
0       ['make a choice and proceed with recipe', 'dep...   
1       ['make a choice and proceed with recipe', 'dep...   
2       ['make a choice and proceed with recipe', 'dep...   
3       ['preheat oven to 425 degrees f', 'press dough...   
4       ['preheat oven to 425 degrees f', 'press dough...   
...                                                   ...   
698896  ['in a bowl , combine the mashed yolks and may...   
698897  ['in a bowl , combine the mashed yolks and may...   
698898  ['in a bowl , combine the mashed yolks and may...   
698899  ['in a bowl , combine the mashed yolks and may...   
698900  ['in a bowl , combine the mashed yolks and may...   

                                              description  \
0       autumn is my favorite time of year to cook! th...   
1       autumn is my favorite time of year to cook! th...   
2       autumn is my favorite time of year to cook! th...   
3       this recipe calls for the crust to be prebaked...   
4       this recipe calls for the crust to be prebaked...   
...                                                   ...   
698896                          deviled eggs, cajun-style   
698897                          devil

In [ ]:
df = Merged_Data2[Merged_Data2['minutes']<=20]

In [ ]:
df.shape

(171931, 18)

In [ ]:
df2 = df[['name','user_id','recipe_id','rating','minutes']]

In [ ]:
df2

name  user_id  recipe_id  rating  \
7                   apple a day  milk shake     6357       5289     5.0   
8                   apple a day  milk shake   192972       5289     5.0   
21                  calm your nerves  tonic    65056      39959     5.0   
76      homemade  vegetable soup from a can   189616      87098     5.0   
77      homemade  vegetable soup from a can   369715      87098     4.0   
...                                     ...      ...        ...     ...   
698890                   zydeco green beans   283251     185979     0.0   
698891                         zydeco salad   226863     367912     5.0   
698892                         zydeco salad   621626     367912     5.0   
698893                         zydeco sauce   865936     357451     5.0   
698894                         zydeco sauce   369558     357451     5.0   

        minutes  
7             0  
8             0  
21            5  
76           12  
77           12  
...         ...  
698890       20  
698891        5  
698892        5  
698893       15  
698894       15  

[171931 rows x 5 columns]

In [ ]:
df = df2[df2['minutes']!=0]

In [ ]:
df

name  user_id  recipe_id  \
21                         calm your nerves  tonic    65056      39959   
76             homemade  vegetable soup from a can   189616      87098   
77             homemade  vegetable soup from a can   369715      87098   
170     i stole the idea from mirj  sesame noodles    49304      90921   
171     i stole the idea from mirj  sesame noodles    82648      90921   
...                                            ...      ...        ...   
698890                          zydeco green beans   283251     185979   
698891                                zydeco salad   226863     367912   
698892                                zydeco salad   621626     367912   
698893                                zydeco sauce   865936     357451   
698894                                zydeco sauce   369558     357451   

        rating  minutes  
21         5.0        5  
76         5.0       12  
77         4.0       12  
170        5.0       18  
171        5.0       18  
...        ...      ...  
698890     0.0       20  
698891     5.0        5  
698892     5.0        5  
698893     5.0       15  
698894     5.0       15  

[169372 rows x 5 columns]

In [ ]:
df.to_csv('short-recipes.csv')

In [ ]:
matrix = df.pivot_table(values='rating', index='user_id', columns='recipe_id')

In [ ]:
matrix

recipe_id   52      92      93      181     205     207     240     245     \
user_id                                                                      
1533           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
1535           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
1634           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
1676           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
1792           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
...            ...     ...     ...     ...     ...     ...     ...     ...   
2002151809     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
2002157583     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
2002194605     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
2002227190     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
2002254807     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   

recipe_id   293     346     ...  532736  532740  533125  533130  533250  \
user_id                     ...                                           
1533           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN   
1535           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN   
1634           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN   
1676           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN   
1792           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN   
...            ...     ...  ...     ...     ...     ...     ...     ...   
2002151809     NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN   
2002157583     NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN   
2002194605     NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN   
2002227190     NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN   
2002254807     NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN   

recipe_id   533583  535230  536044  536060  536729  
user_id                                             
1533           NaN     NaN     NaN     NaN     NaN  
1535           NaN     NaN     NaN     NaN     NaN  
1634           NaN     NaN     NaN     NaN     NaN  
1676           NaN     NaN     NaN     NaN     NaN  
1792           NaN     NaN     NaN     NaN     NaN  
...            ...     ...     ...     ...     ...  
2002151809     NaN     NaN     NaN     NaN     NaN  
2002157583     NaN     NaN     NaN     NaN     NaN  
2002194605     NaN     NaN     NaN     NaN     NaN  
2002227190     NaN     NaN     NaN     NaN     NaN  
2002254807     NaN     NaN     NaN     NaN     NaN  

[17108 rows x 41102 columns]

In [ ]:
# data.groupby(['user_id','recipe_id'])['rating'].max().unstack()

In [ ]:
len(df["recipe_id"].unique())

41102

In [ ]:
len(df["user_id"].unique())


17108

In [ ]:
freq = df['user_id'].value_counts()
threshold = 15
mask = df['user_id'].isin(freq[freq >= threshold].index)
df = df.loc[mask]

In [ ]:
df

name  user_id  recipe_id  \
21                         calm your nerves  tonic    65056      39959   
76             homemade  vegetable soup from a can   189616      87098   
77             homemade  vegetable soup from a can   369715      87098   
170     i stole the idea from mirj  sesame noodles    49304      90921   
171     i stole the idea from mirj  sesame noodles    82648      90921   
...                                            ...      ...        ...   
698886           zwiebeln salat  swiss onion salad   169430     455209   
698890                          zydeco green beans   283251     185979   
698891                                zydeco salad   226863     367912   
698892                                zydeco salad   621626     367912   
698893                                zydeco sauce   865936     357451   

        rating  minutes  
21         5.0        5  
76         5.0       12  
77         4.0       12  
170        5.0       18  
171        5.0       18  
...        ...      ...  
698886     5.0       10  
698890     0.0       20  
698891     5.0        5  
698892     5.0        5  
698893     5.0       15  

[122610 rows x 5 columns]

In [ ]:
len(df["recipe_id"].unique())

38665

In [ ]:
len(df["user_id"].unique())

1706

In [ ]:
df

name  user_id  recipe_id  \
21                         calm your nerves  tonic    65056      39959   
76             homemade  vegetable soup from a can   189616      87098   
77             homemade  vegetable soup from a can   369715      87098   
170     i stole the idea from mirj  sesame noodles    49304      90921   
171     i stole the idea from mirj  sesame noodles    82648      90921   
...                                            ...      ...        ...   
698886           zwiebeln salat  swiss onion salad   169430     455209   
698890                          zydeco green beans   283251     185979   
698891                                zydeco salad   226863     367912   
698892                                zydeco salad   621626     367912   
698893                                zydeco sauce   865936     357451   

        rating  minutes  
21         5.0        5  
76         5.0       12  
77         4.0       12  
170        5.0       18  
171        5.0       18  
...        ...      ...  
698886     5.0       10  
698890     0.0       20  
698891     5.0        5  
698892     5.0        5  
698893     5.0       15  

[122610 rows x 5 columns]

In [ ]:
matrix=df.groupby(['user_id','recipe_id'])['rating'].max().unstack()

In [ ]:
matrix

recipe_id   52      92      93      181     205     207     240     245     \
user_id                                                                      
1533           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
1535           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
1634           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
2310           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
2312           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
...            ...     ...     ...     ...     ...     ...     ...     ...   
1800054678     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
1802849661     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
2000431901     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
2000498330     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
2001102678     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   

recipe_id   293     346     ...  532487  532736  532740  533125  533130  \
user_id                     ...                                           
1533           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN   
1535           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN   
1634           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN   
2310           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN   
2312           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN   
...            ...     ...  ...     ...     ...     ...     ...     ...   
1800054678     NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN   
1802849661     NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN   
2000431901     NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN   
2000498330     NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN   
2001102678     NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN   

recipe_id   533250  535230  536044  536060  536729  
user_id                                             
1533           NaN     NaN     NaN     NaN     NaN  
1535           NaN     NaN     NaN     NaN     NaN  
1634           NaN     NaN     NaN     NaN     NaN  
2310           NaN     NaN     NaN     NaN     NaN  
2312           NaN     NaN     NaN     NaN     NaN  
...            ...     ...     ...     ...     ...  
1800054678     NaN     NaN     NaN     NaN     NaN  
1802849661     NaN     NaN     NaN     NaN     NaN  
2000431901     NaN     NaN     NaN     NaN     NaN  
2000498330     NaN     NaN     NaN     NaN     NaN  
2001102678     NaN     NaN     NaN     NaN     NaN  

[1706 rows x 38665 columns]

In [ ]:
matrix.keys()

Int64Index([    52,     92,     93,    181,    205,    207,    240,    245,
               293,    346,
            ...
            532487, 532736, 532740, 533125, 533130, 533250, 535230, 536044,
            536060, 536729],
           dtype='int64', name='recipe_id', length=38665)

In [ ]:
matrix.loc[1533].unique()

array([nan,  5.,  4.,  2.])

In [ ]:
matrix=matrix.fillna(0)

In [ ]:
matrix

recipe_id   52      92      93      181     205     207     240     245     \
user_id                                                                      
1533           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1535           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1634           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
2310           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
2312           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
...            ...     ...     ...     ...     ...     ...     ...     ...   
1800054678     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1802849661     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
2000431901     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
2000498330     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
2001102678     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

recipe_id   293     346     ...  532487  532736  532740  533125  533130  \
user_id                     ...                                           
1533           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0   
1535           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0   
1634           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0   
2310           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0   
2312           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0   
...            ...     ...  ...     ...     ...     ...     ...     ...   
1800054678     0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0   
1802849661     0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0   
2000431901     0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0   
2000498330     0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0   
2001102678     0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0   

recipe_id   533250  535230  536044  536060  536729  
user_id                                             
1533           0.0     0.0     0.0     0.0     0.0  
1535           0.0     0.0     0.0     0.0     0.0  
1634           0.0     0.0     0.0     0.0     0.0  
2310           0.0     0.0     0.0     0.0     0.0  
2312           0.0     0.0     0.0     0.0     0.0  
...            ...     ...     ...     ...     ...  
1800054678     0.0     0.0     0.0     0.0     0.0  
1802849661     0.0     0.0     0.0     0.0     0.0  
2000431901     0.0     0.0     0.0     0.0     0.0  
2000498330     0.0     0.0     0.0     0.0     0.0  
2001102678     0.0     0.0     0.0     0.0     0.0  

[1706 rows x 38665 columns]

In [ ]:
np.save('matrix.npy',matrix)

In [ ]:
item_similarities = np.dot(Vt.T, Vt)

In [ ]:
# data=data.pivot(index="user_id",columns='recipe_id',values='rating').fillna(0)
# U,S,Vt=np.linalg.svd(matrix,full_matrices=False)

In [ ]:
# Vt

array([[-2.43959391e-03, -3.20668687e-04, -1.05994542e-03, ...,
        -5.51817580e-04, -2.32580458e-04, -7.91206720e-03],
       [-5.20602742e-04, -1.32677121e-04, -6.41603348e-04, ...,
        -8.65862486e-05, -4.82192184e-05, -8.37903389e-04],
       [ 8.37261939e-04,  3.07557915e-04,  7.80237678e-04, ...,
         4.68987588e-04,  1.77414743e-04,  5.23352377e-03],
       ...,
       [-1.21096182e-05, -8.29264317e-04,  1.52362396e-03, ...,
        -2.64250856e-04, -1.98798977e-04, -1.18778592e-04],
       [ 3.84436239e-05, -1.36323901e-03,  1.42305457e-03, ...,
         1.42672502e-04,  1.48613065e-04,  1.46188244e-04],
       [ 8.43849784e-05, -1.79186751e-04,  3.81630818e-04, ...,
        -3.36316124e-05, -3.24164078e-05, -1.86945120e-05]])

In [ ]:
# S

array([2.66757640e+02, 2.06076660e+02, 2.00203691e+02, ...,
       9.28461024e+00, 2.00287459e-17, 4.72673105e-29])

In [ ]:
# rank=np.count_nonzero(S)

In [ ]:
# rank

1706

In [ ]:
# rank=65

In [ ]:
# S=np.diag(S[:rank])
# U=U[:,:rank]
# Vt=Vt[:rank,:]

In [ ]:
# approximation=np.dot(np.dot(U,S),Vt)

In [ ]:
# /approximation

array([[-2.97080454e-03,  2.63840013e-03,  2.09428932e-02, ...,
         1.37060673e-04,  8.18557743e-04, -1.68740937e-03],
       [-7.47568824e-03,  2.94543220e-02,  2.11793637e-01, ...,
        -9.31170695e-03,  6.78966299e-04, -2.21633492e-02],
       [-3.36453554e-03,  1.20903950e-03,  2.14640393e-02, ...,
        -4.59746485e-04, -3.70008250e-04, -4.01465776e-03],
       ...,
       [ 1.88808240e-02,  6.03556979e-03,  6.07514078e-02, ...,
        -9.08571893e-04,  4.06356202e-04,  2.05445195e-03],
       [ 1.03691310e-04,  3.23369281e-04,  1.66834879e-02, ...,
        -1.83637118e-03, -6.31877057e-04, -2.16219100e-03],
       [-4.99216454e-03,  1.03628460e-02, -1.21754433e-03, ...,
        -2.12070035e-03, -1.64117594e-03, -2.37729129e-02]])

In [ ]:
# predict the ratings for all uninteracted items for a user
def predict_all(user_id, matrix, item_similarities, k=5):
    # get the ratings of the user
    user_ratings = matrix[user_id, :]

    # get the indices of the uninteracted items
    uninteracted_items = np.where(user_ratings == 0)[0]

    # predict the rating for each uninteracted item
    predictions = np.zeros((len(uninteracted_items),))
    for i, item_id in enumerate(uninteracted_items):
        # find the k most similar items to the target item
        similar_items = np.argsort(-item_similarities[item_id, :])[:k]

        # get the ratings of the k most similar items
        similar_ratings = matrix[user_id, similar_items]

        # compute the weighted average of the ratings
        similarity_scores = item_similarities[item_id, similar_items]
        prediction = np.dot(similarity_scores, similar_ratings) / np.sum(similarity_scores)

        # add the average rating of the item to the prediction
        prediction += np.mean(matrix[:, item_id])

        # store the prediction
        predictions[i] = prediction

    # create a dataframe with the item IDs and predicted ratings
    predicted_ratings = pd.DataFrame({'item_id': uninteracted_items, 'rating': predictions})

    return predicted_ratings

In [ ]:
from scipy.sparse import csr_matrix

# convert the input matrix to a sparse matrix
sparse_matrix = csr_matrix(matrix)

# define the batch size
batch_size = 1000

# compute the similarity matrix between items incrementally
item_similarities = csr_matrix((matrix.shape[1], matrix.shape[1]), dtype=np.float32)
for i in range(0, matrix.shape[1], batch_size):
    print(f"Processing items {i}-{i+batch_size-1}")
    batch = sparse_matrix[:, i:i+batch_size]
    print(batch.shape)
    batch_item_similarities = batch.T.dot(Vt)
    item_similarities[i:i+batch_size, :] = batch_item_similarities

In [ ]:
print(Vt.T.shape)

In [ ]:
import numpy as np

# Define the number of users, items, and latent factors
num_users = 100
num_items = 50
num_factors = 100

# Generate random user-item ratings matrix
R = np.random.randint(0, 6, size=(num_users, num_items))

# Initialize the latent factor matrices U and V with small random values
U = np.random.randn(num_users, num_factors) * 0.01
V = np.random.randn(num_items, num_factors) * 0.01

# Define the regularization parameter
lamda = 0.01

# Define the learning rate and number of iterations
learning_rate = 0.0001
num_iterations = 10000

# Define the objective function
def objective_function(R, U, V, lamda):
    error = np.sum((R - np.dot(U, V.T))**2)
    regularization = lamda * (np.sum(U**2) + np.sum(V**2))
    return 0.5 * (error + regularization)

# Perform gradient descent
for iteration in range(num_iterations):
    # Compute the gradients with respect to U and V
    error = R - np.dot(U, V.T)
    grad_U = -np.dot(error, V) + lamda * U
    grad_V = -np.dot(error.T, U) + lamda * V
    
    # Update the latent factor matrices U and V
    U -= learning_rate * grad_U
    V -= learning_rate * grad_V
    
    # Compute the objective function and print the progress
    obj = objective_function(R, U, V, lamda)
    print("Iteration {0}/{1}: objective function = {2}".format(iteration+1, num_iterations, obj))

Streaming output truncated to the last 5000 lines.
Iteration 5001/10000: objective function = 92.96266854608774
Iteration 5002/10000: objective function = 92.86966758351552
Iteration 5003/10000: objective function = 92.77676343760021
Iteration 5004/10000: objective function = 92.68395601863274
Iteration 5005/10000: objective function = 92.59124523693585
Iteration 5006/10000: objective function = 92.49863100286449
Iteration 5007/10000: objective function = 92.4061132268057
Iteration 5008/10000: objective function = 92.31369181917904
Iteration 5009/10000: objective function = 92.22136669043654
Iteration 5010/10000: objective function = 92.12913775106296
Iteration 5011/10000: objective function = 92.037004911576
Iteration 5012/10000: objective function = 91.94496808252643
Iteration 5013/10000: objective function = 91.85302717449822
Iteration 5014/10000: objective function = 91.76118209810879
Iteration 5015/10000: objective function = 91.66943276400906
Iteration 5016/10000: objective funct

In [ ]:
U

In [ ]:
V

In [ ]:
R

array([[5, 3, 4, ..., 1, 1, 5],
       [5, 4, 5, ..., 0, 2, 1],
       [5, 0, 1, ..., 2, 0, 4],
       ...,
       [4, 2, 5, ..., 0, 4, 3],
       [5, 0, 2, ..., 1, 0, 3],
       [1, 3, 5, ..., 5, 2, 1]])

In [ ]:
XX

array([[2.32369582e+00, 2.62526725e+00, 1.36536045e+00, ...,
        9.84563646e-01, 2.62927818e+00, 2.64909841e+00],
       [3.65578358e+00, 4.02234000e+00, 1.66121280e+00, ...,
        5.29950305e-02, 1.67902849e+00, 1.01195190e+00],
       [4.95260755e+00, 1.65421315e-03, 1.03093091e+00, ...,
        2.36448711e+00, 3.16784606e+00, 4.23537403e+00],
       ...,
       [5.60734866e-01, 1.27874307e+00, 3.55322357e+00, ...,
        1.91323151e+00, 4.01138369e+00, 1.39764127e+00],
       [2.52581996e+00, 1.41644215e+00, 3.49925995e+00, ...,
        2.01100772e+00, 2.72799381e+00, 3.73690859e+00],
       [3.10507679e+00, 3.06097302e+00, 1.56800324e+00, ...,
        4.96403838e+00, 2.47875595e+00, 3.60213058e+00]])

In [ ]:
import numpy as np

# Define the number of users, items, and latent factors
num_users = 100
num_items = 50
num_factors = 100

# Generate random user-item ratings matrix
R = np.random.randint(0, 6, size=(num_users, num_items))

# Generate a mask matrix indicating which values are missing
missing_mask = np.random.choice([True, False], size=(num_users, num_items), p=[0.3, 0.7])

# Initialize the latent factor matrices U and V with small random values
U = np.random.randn(num_users, num_factors) * 0.01
V = np.random.randn(num_items, num_factors) * 0.01

# Define the regularization parameter
lamda = 0.01

# Define the learning rate and number of iterations
learning_rate = 0.008
num_iterations = 1000

# Define the objective function
def objective_function(R, U, V, lamda, missing_mask):
    error = np.sum(((R - np.dot(U, V.T)) * missing_mask)**2)
    regularization = lamda * (np.sum(U**2) + np.sum(V**2))
    return 0.5 * (error + regularization)

# Perform gradient descent
for iteration in range(num_iterations):
    # Compute the gradients with respect to U and V
    error = (R - np.dot(U, V.T)) * missing_mask
    grad_U = -np.dot(error, V) + lamda * U
    grad_V = -np.dot(error.T, U) + lamda * V
    
    # Update the latent factor matrices U and V
    U -= learning_rate * grad_U
    V -= learning_rate * grad_V
    
    # Compute the objective function and print the progress
    obj = objective_function(R, U, V, lamda, missing_mask)
    print("Iteration {0}/{1}: objective function = {2}".format(iteration+1, num_iterations, obj))

Iteration 1/1000: objective function = 7018.849368633051
Iteration 2/1000: objective function = 7016.295207098518
Iteration 3/1000: objective function = 7012.800331627474
Iteration 4/1000: objective function = 7007.313644815909
Iteration 5/1000: objective function = 6997.821520133516
Iteration 6/1000: objective function = 6980.262145262819
Iteration 7/1000: objective function = 6946.322781396393
Iteration 8/1000: objective function = 6879.035931407635
Iteration 9/1000: objective function = 6744.495104985876
Iteration 10/1000: objective function = 6478.578944522253
Iteration 11/1000: objective function = 5975.142094895394
Iteration 12/1000: objective function = 5112.794927419471
Iteration 13/1000: objective function = 3909.8145809351804
Iteration 14/1000: objective function = 2762.0884819007674
Iteration 15/1000: objective function = 2146.6783921828987
Iteration 16/1000: objective function = 1939.6675072538128
Iteration 17/1000: objective function = 1856.2284876788274
Iteration 18/1000:

In [ ]:
XX=np.dot(U, V.T)

In [ ]:
XX

array([[3.07200231e+00, 2.58215670e+00, 1.00154851e+00, ...,
        5.10907929e-04, 3.99750955e+00, 2.93909484e+00],
       [7.06799382e-01, 1.10143344e+00, 2.45749037e+00, ...,
        2.99755538e+00, 1.40411938e+00, 2.44521532e+00],
       [1.70627834e+00, 2.15114155e+00, 4.21853070e+00, ...,
        1.58891755e+00, 2.75826296e+00, 1.72748764e+00],
       ...,
       [1.99897870e+00, 1.00089356e+00, 1.10961244e+00, ...,
        1.41823484e+00, 1.71011318e+00, 2.20871505e+00],
       [1.82882550e+00, 1.71541246e+00, 4.99721039e+00, ...,
        4.02172910e+00, 2.31035858e+00, 1.22487374e+00],
       [9.94646993e-01, 1.82105342e+00, 2.76367528e+00, ...,
        4.99886864e+00, 9.52182258e-01, 1.77198430e+00]])

In [ ]:
R

array([[0, 5, 1, ..., 0, 4, 0],
       [0, 5, 4, ..., 0, 5, 0],
       [2, 2, 0, ..., 5, 4, 0],
       ...,
       [2, 1, 4, ..., 2, 5, 5],
       [1, 1, 5, ..., 3, 3, 2],
       [0, 3, 0, ..., 5, 5, 5]])