<a href="https://colab.research.google.com/github/vipashaaV321/Collaborative-Food-Recipe-Recommendation-System/blob/Sarvesh/matrix_completion_experiments.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from scipy.sparse.linalg import svds

# Define a sparse rating matrix with data type float
rating_matrix = np.array([[4.0, 0.0, 1.0, 0.0, 5.0],
                          [0.0, 2.0, 0.0, 3.0, 0.0],
                          [3.0, 0.0, 3.0, 0.0, 0.0],
                          [0.0, 5.0, 0.0, 2.0, 0.0]], dtype=float)

# Define the number of latent factors
k = 2

# Perform singular value decomposition
U, s, V = svds(rating_matrix, k)

# Construct diagonal matrix from singular values
s_diag_matrix = np.diag(s)

# Fill in the missing values in the rating matrix
predicted_ratings = np.dot(np.dot(U, s_diag_matrix), V)

print("Original rating matrix:\n", rating_matrix)
print("Predicted rating matrix:\n", predicted_ratings)


Original rating matrix:
 [[4. 0. 0. 0. 5.]
 [0. 2. 0. 3. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 2. 0.]]
Predicted rating matrix:
 [[ 4.00000000e+00 -3.51628090e-17  4.57966998e-16  4.29274743e-16
   5.00000000e+00]
 [-7.03256180e-17  1.60000000e+00 -7.62668258e-32  3.20000000e+00
  -8.79070225e-17]
 [ 6.10622664e-16 -5.08445505e-32  6.99112570e-32 -2.54222753e-32
   7.63278329e-16]
 [ 9.64037913e-16  8.00000000e-01  7.62668258e-32  1.60000000e+00
   1.20504739e-15]]


In [ ]:
RMSE = np.sqrt(np.sum((predicted_ratings - rating_matrix)**2) / 20)
import numpy as np
from scipy.sparse.linalg import svds

# Define a sparse rating matrix with data type float
rating_matrix = np.array([[4.0, 0.0, 1.0, 0.0, 5.0],
                          [0.0, 2.0, 0.0, 3.0, 0.0],
                          [3.0, 0.0, 3.0, 0.0, 0.0],
                          [0.0, 5.0, 0.0, 2.0, 0.0]], dtype=float)

# Define the number of latent factors
k = 2

# Perform singular value decomposition
U, s, V = svds(rating_matrix, k)

# Construct diagonal matrix from singular values
s_diag_matrix = np.diag(s)

# Fill in the missing values in the rating matrix
predicted_ratings = np.dot(np.dot(U, s_diag_matrix), V)

print("Original rating matrix:\n", rating_matrix)
print("Predicted rating matrix:\n", predicted_ratings)


Original rating matrix:
 [[4. 0. 1. 0. 5.]
 [0. 2. 0. 3. 0.]
 [3. 0. 3. 0. 0.]
 [0. 5. 0. 2. 0.]]
Predicted rating matrix:
 [[ 4.42069331e+00 -2.50161901e-16  1.98365074e+00 -1.00064761e-16
   4.06173762e+00]
 [ 0.00000000e+00  2.78885438e+00  0.00000000e+00  1.72360680e+00
   0.00000000e+00]
 [ 2.12469505e+00 -1.20234026e-16  9.53391833e-01 -4.80936103e-17
   1.95217202e+00]
 [-2.72269936e-16  4.51246118e+00 -1.22172796e-16  2.78885438e+00
  -2.50161901e-16]]


In [ ]:
RMSE

0.7071067811865476

In [ ]:
predicted_ratings[1][0]

-7.032561799574852e-17